apiVersion: apps/v1
kind: Deployment
metadata:
  name: cors-proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cors-proxy
  template:
    metadata:
      labels:
        app: cors-proxy
    spec:
      containers:
      - name: cors-proxy
        image: robcherry/cors-anywhere
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cors-proxy-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cors-proxy
