apiVersion: apps/v1
kind: Deployment
metadata:
  name: cors-anywhere
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cors-anywhere
  template:
    metadata:
      labels:
        app: cors-anywhere
    spec:
      containers:
      - name: cors-proxy
        image: redocly/cors-anywhere
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
