apiVersion: apps/v1
kind: Deployment
metadata:
  name: cors-anywhere
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cors-anywhere
  template:
    metadata:
      labels:
        app: cors-anywhere
    spec:
      containers:
      - name: cors-anywhere
        image: redocly/cors-anywhere
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cors-anywhere-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: cors-anywhere
