apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cors-anywhere-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cors-anywhere
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
